default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  statement_timeout: <%= ENV['STATEMENT_TIMEOUT'] || 250 %> # ms in Psql
  connect_timeout: 1 # seconds in ActiveRecord
  checkout_timeout: 1 # Seconds in ActiveRecord

development:
  <<: *default
  database: activity_network_app_development
  username: <%= ENV['DB_USER'] || "postgres" %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || "localhost" %>
  port: <%= ENV['DB_PORT'] || 5432 %>

test:
  <<: *default
  database: activity_network_app_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
